---
spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/maps
    username: postgres
    password: postgres

googleApi:
  geoCoding:
    url: https://maps.googleapis.com/maps/api/geocode/json?address=
  key: AIzaSyCAXlFSrxi2e8j8wfwFr5Jj-o0a2Kug5x8